language: php

sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_script:
  - composer install
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=psr2