<?php

/**
 * Monkey Boards
 * /include/langs/en.php
 * Language file - English (British)
 *
 * @version 1.0
 * @author Jamie Hurst
 */

$strings = array(
		'app_name' 					=> 	'Monkey Boards',
		'forums' 					=> 	'Forums',
		'admin' 					=> 	'Administration',
		'id' 						=> 	'ID',
		'name' 						=> 	'Name',
		'desc' 						=> 	'Description',
		'save' 						=> 	'Save changes',
		'forum_delete_confirm1' 	=> 	'Are you completely <strong>sure</strong> you want to delete the forum',
		'forum_delete_confirm2' 	=> 	'and its topics and posts?',
		'perm_warning' 				=> 	'<strong>This is a permanent process and cannot be undone.</strong>',
		'delete' 					=> 	'Delete',
		'cancel' 					=> 	'Cancel',
		'actions' 					=> 	'Actions',
		'edit' 						=> 	'Edit',
		'no_forums' 				=> 	'There are no forums to display.',
		'add_forum' 				=> 	'Add forum',
		'forum' 					=> 	'Forum',
		'topics' 					=> 	'Topics',
		'posts'						=> 	'Posts',
		'last_post' 				=> 	'Last post',
		'total_users' 				=> 	'Total number of registered users:',
		'total_topics' 				=> 	'Total number of topics:',
		'total_posts' 				=> 	'Total number of posts:',
		'submit' 					=> 	'Submit',
		'auto_links' 				=> 	'Auto-links',
		'html' 						=> 	'HTML',
		'smilies' 					=> 	'Smilies',
		'register' 					=> 	'Register',
		'register_as_user' 			=> 	'Register as user',
		'username' 					=> 	'Username',
		'email' 					=> 	'Email',
		'email_add' 				=> 	'Email address',
		'user_list' 				=> 	'User list',
		'title' 					=> 	'Title',
		'registered' 				=> 	'Registered',
		'rules' 					=> 	'Rules',
		'search' 					=> 	'Search',
		'enter_search' 				=> 	'Enter your search criteria',
		'keyword_search' 			=> 	'Keyword search',
		'author_search' 			=> 	'Author search',
		'search_location' 			=> 	'Select where to search',
		'all_forums' 				=> 	'All forums',
		'search_scope' 				=> 	'Search in',
		'scope_both' 				=> 	'Message text and topic subject',
		'scope_text' 				=> 	'Message text only',
		'scope_subject' 			=> 	'Topic subject only',
		'forgotten_pw' 				=> 	'Forgotten password',
		'forgotten_pw_blurb' 		=> 	'If you have forgotten your password, please enter your username and email address below.<br/>You will be emailed a new password to use.',
		'login' 					=> 	'Login',
		'forgot_pw' 				=> 	'Forgot your password?',
		'password' 					=> 	'Password',
		'admin_welcome' 			=> 	'Welcome to the Monkey Boards administration area. From here you can control vital aspects of the forum. You can:',
		'forums_title' 				=> 	'create, edit and delete forums',
		'settings_title' 			=> 	'set forum-wide options and preferences',
		'ban_title' 				=> 	'ban users or edit user details',
		'censor_title' 				=> 	'censor words',
		'stats_title' 				=> 	'view forum statistics',
		'stats' 					=> 	'Statistics',
		'script'  					=> 	'Script',
		'version' 					=> 	'version',
		'php' 						=> 	'PHP',
		'sqlite' 					=> 	'SQLite',
		'database' 					=> 	'Database',
		'rows' 						=> 	'rows',
		'users' 					=> 	'Users',
		'user_details' 				=> 	'User details',
		'member' 					=> 	'Member',
		'moderator' 				=> 	'Moderator',
		'administrator' 			=> 	'Administrator',
		'new_pw' 					=> 	'New password',
		'only_admin_delete' 		=> 	'Sorry you cannot delete the only administrator user, ',
		'user_delete_confirm' 		=> 	'Are you completely <strong>sure</strong> you want to delete the user',
		'banned_shown' 				=> 	'Banned users are shown like so: <del>username</del>.',
		'ban' 						=> 	'Ban',
		'unban' 					=> 	'Unban',
		'editing_post' 				=> 	'Editing post',
		'topic_mod' 				=> 	'Topic moderation',
		'topic_delete_confirm1' 	=> 	'Are you completely <strong>sure</strong> you want to delete the topic',
		'topic_delete_confirm2' 	=> 	'and its posts?',
		'move_select' 				=> 	'Select which forum you would like to move the topic',
		'move' 						=> 	'Move',
		'stick' 					=> 	'Stick',
		'unstick' 					=> 	'Unstick',
		'lock' 						=> 	'Lock',
		'unlock' 					=> 	'Unlock',
		'home' 						=> 	'Home',
		'author' 					=> 	'Author',
		'message' 					=> 	'Message',
		'post_reply' 				=> 	'Post reply',
		'topic_locked' 				=> 	'This topic is locked, you cannot post a reply.',
		'powered_by' 				=> 	'Powered by <a href="http://monkeyboards.zenco.net/">Monkey Boards</a>',
		'return_forums' 			=> 	'Return to forums',
		'replies' 					=> 	'Replies',
		'views' 					=> 	'Views',
		'sticky' 					=> 	'Sticky',
		'no_topics' 				=> 	'There are no topics to display.',
		'new_topic' 				=> 	'Post new topic',
		'subject' 					=> 	'Subject',
		'settings' 					=> 	'Settings',
		'essentials' 				=> 	'Essentials',
		'site_title' 				=> 	'Site title',
		'forum_rules' 				=> 	'Forum rules',
		'site_style' 				=> 	'Site style',
		'welcome_email' 			=> 	'Welcome email',
		'email_from' 				=> 	'From address',
		'topic' 					=> 	'Topic',
		'one_second_ago' 			=> 	'Just now',
		'seconds_ago' 				=> 	'seconds ago',
		'one_min_ago' 				=> 	'1 min ago',
		'mins_ago' 					=> 	'mins ago',
		'today_at' 					=> 	'Today at',
		'yesterday_at' 				=> 	'Yesterday at',
		'by' 						=> 	'by',
		'logout' 					=> 	'Logout',
		'forumrules' 				=> 	'<p>By registering and posting on these forums, you agree to the following rules:</p>
											<ul>
												<li>Be nice to others</li>
												<li>Do not post offensive or illegal material</li>
												<li>No adult content or profanities</li>
												<li>No flaming, spamming or advertising</li>
												<li>Do not hijack other people\'s threads</li>
											</ul>
											<p>You must be thirteen years of age or more to post information on these forums.</p>',
		'registerform' 				=> 	'<p>To post on these forums you must register. Please type a username and your email address in the form below.</p>
											<p>We will <strong>not</strong> sell or otherwise disclose your email address to anyone else. It is needed for verification and so that we can send you a temporary password.</p>',
		'invalid_login' 			=> 	'Invalid username or password.',
		'invalid_username' 			=> 	'Invalid username. Must be lowercase, contain alphanumeric characters only and not start with a number.',
		'user_exists' 				=> 	'Username already taken or email address already in use.',
		'mail_error' 				=> 	'There was an error sending mail. Please contact the webmaster.',
		'register_success' 			=> 	'Registration successful. Please check your email inbox for your temporary password.',
		'db_error' 					=> 	'There was an error with the database.',
		'short_username' 			=> 	'Invalid username. Must be at least five characters in length.',
		'invalid_email' 			=> 	'Invalid email address.',
		'missing_message' 			=> 	'You didn\'t type your message. Please go back and type it.',
		'missing_subject' 			=> 	'You forgot to enter a subject. Please go back and enter one.',
		'welcome_email_message' 	=> 	"Welcome to {site_title}.\n\nYour account information is as follows:\n\nUsername: {username}\nPassword: {password}\n\nThis is only a temporary password, please change it the first time you log in.\n\nThank you for registering.",
		'welcome_email_subject' 	=> 	'Welcome to {site_title}',
		'user_banned' 				=> 	'You have been banned. Please contact a forum administrator.',
		'categories' 				=> 	'Categories',
		'category_delete_confirm1' 	=> 	'Are you completely <strong>sure</strong> you want to delete the category',
		'category_delete_confirm2' 	=> 	'and its child forums?',
		'no_categories' 			=> 	'There are no categories to display.',
		'add_category' 				=> 	'Add category',
		'category' 					=> 	'Category',
		'date_format' 				=> 	'Date format',
		'base_address' 				=> 	'Base address',
		'subject_len' 				=> 	'Your chosen subject is too long, it must be 60 characters or less.',
		'message_len' 				=> 	'Your message is too long, it cannot exceed one kilobyte.',
		'profile' 					=> 	'Profile',
		'index' 					=> 	'Index'
	);