<?php

/**
 * Monkey Boards
 * /include/langs/fr.php
 * Language file - French
 * 
 * @package MonkeyBoards/include/lang
 * @version 1.0
 * @author Jamie Hurst
 */

$strings = array(
		'app_name' 					=> 	'Monkey Boards',
		'forums' 					=> 	'Forums',
		'admin' 					=> 	'Aller au Panneau d\'administration',
		'id' 						=> 	'ID',
		'name' 						=> 	'Nom',
		'desc'						=> 	'Description',
		'save' 						=> 	'Sauvegarder changements',
		'forum_delete_confirm1' 	=> 	'Êtes vous complètement <strong>sûr</strong> vous voulez supprimer le forum',
		'forum_delete_confirm2' 	=> 	'et ses sujets et messages?',
		'perm_warning' 				=> 	'<strong>C\'est un processus permanent et ne peut pas être renversé.</strong>',
		'delete' 					=> 	'Supprimer',
		'cancel' 					=> 	'Annuler',
		'actions' 					=> 	'Actions',
		'edit' 						=> 	'Éditer',
		'no_forums' 				=> 	'Forum n\'existe pas. Vous pouvez ajouter ci-dessous en utilisant la forme.',
		'add_forum' 				=> 	'Ajouter le forum',
		'forum' 					=> 	'Forum',
		'sujets' 					=> 	'Sujets',
		'posts' 					=> 	'Messages',
		'last_post' 				=> 	'Dernier message',
		'total_users' 				=> 	'Nombre d\'utilisateurs enregistrés:',
		'total_topics' 				=> 	'Nombre de sujets:',
		'total_posts' 				=> 	'Nombre de messages:',
		'submit' 					=> 	'Envoyer',
		'auto_links' 				=> 	'Auto-hyperliens',
		'html' 						=> 	'HTML',
		'smilies' 					=> 	'Émoticônes',
		'register' 					=> 	'S\'enregistrer',
		'register_as_user' 			=> 	'Registre en tant qu\'utilisateur enregistré',
		'username'					=> 	'Nom d\'utilisateur',
		'email' 					=> 	'E-mail',
		'email_add' 				=> 	'Adresse d\'E-mail',
		'user_list' 				=> 	'Liste des membres',
		'title' 					=> 	'Niveau',
		'registered' 				=> 	'inscrit le',
		'rules' 					=> 	'Règles',
		'search' 					=> 	'Rechercher',
		'enter_search' 				=> 	'Écrire les critères de recherche',
		'keyword_search' 			=> 	'Recherche par mot-clé',
		'author_search' 			=> 	'Recherche d\'auteur',
		'search_location' 			=> 	'Choisir où rechercher',
		'all_forums' 				=> 	'Tous les forums',
		'search_scope' 				=> 	'Recherche dedans',
		'scope_both' 				=> 	'Corps du message et sujet du message',
		'scope_text' 				=> 	'Corps du message seulement',
		'scope_subject' 			=> 	'suject du message seulement',
		'forgotten_pw' 				=> 	'J\'ai oublié mon mot de passe',
		'forgotten_pw_blurb' 		=> 	'Si vous avez oublié votre mot de passe svp écrire votre username et email address ci-dessous.<br/>Vous serez emailed un nouveau mot de passe.',
		'login' 					=> 	'Connexion',
		'forgot_pw' 				=> 	'Oublié votre mot de passe?',
		'password' 					=> 	'Mot de passe',
		'admin_welcome' 			=> 	'Vous avez atteint le panneau d\'administration pour Monkey Boards. D\'ici vous pouvez commander des aspects essentiels du forum. Vous pouvez:', 
		'forums_title' 				=> 	'créer, éditer et supprimer forums',
		'settings_title' 			=> 	'commander les options et les préférences forum-larges',
		'ban_title' 				=> 	'interdire les utilisateurs ou changer leurs détails',
		'censor_title' 				=> 	'bloc mots de tabou',
		'stats_title' 				=> 	'lire les statistiques de forum',
		'stats' 					=> 	'Statistiques',
		'script'					=> 	'Programme',
		'version' 					=> 	'version',
		'php' 						=> 	'PHP',
		'sqlite' 					=> 	'SQLite',
		'database' 					=> 	'Magasin de données',
		'rows' 						=> 	'rows',
		'users' 					=> 	'Utilisateurs',
		'user_details' 				=> 	'Données d\'utilisateur',
		'member' 					=> 	'Membre',
		'moderator' 				=> 	'Modérateur',
		'administrator' 			=> 	'Administrateur',
		'new_pw' 					=> 	'Nouveau mot de passe',
		'only_admin_delete' 		=> 	'Vous ne pouvez pas enlever le seul utilisateur qui est un administrateur, ',
		'user_delete_confirm' 		=> 	'Êtes-vous complètement <strong>sûr</strong> supprimer l\'utilisateur',
		'banned_shown' 				=> 	'Des utilisateurs interdits sont montrés comme suit: <del>nom d\'utilisateur</del>.',
		'ban' 						=> 	'Banir',
		'unban' 					=> 	'enlever l\'interdiction',
		'editing_post' 				=> 	'Message changeant',
		'topic_mod' 				=> 	'Modération de sujet',
		'topic_delete_confirm1' 	=> 	'<strong>Sûr</strong> vous êtes toi voulez enlever le sujet',
		'topic_delete_confirm2' 	=> 	'et ses messages?',
		'move_select' 				=> 	'Pour identifier le forum pour déplacer le sujet',
		'move' 						=> 	'Déplacer',
		'stick' 					=> 	'faire Post-It',
		'unstick' 					=> 	'enlever Post-It',
		'lock' 						=> 	'Verrouiller',
		'unlock' 					=> 	'Déverrouiller',
		'home' 						=> 	'Home',
		'author' 					=> 	'Auteur',
		'message' 					=> 	'Message',
		'post_reply' 				=> 	'Répondre au sujet',
		'topic_locked' 				=> 	'Ce sujet est verrouillé; vous ne pouvez pas éditer les messages ou faire de réponses.',
		'powered_by' 				=> 	'Fourni par <a href="http://monkeyboards.zenco.net/">Monkey Boards</a>',
		'return_forums' 			=> 	'Revenir aux forums',
		'replies' 					=> 	'Réponses',
		'views' 					=> 	'Vus',
		'sticky' 					=> 	'Post-it',
		'no_topics' 				=> 	'Pas de Messages',
		'new_topic' 				=> 	'Poster un nouveau sujet',
		'subject' 					=> 	'Sujet du message',
		'settings' 					=> 	'Préférences',
		'essentials' 				=> 	'essentiels',
		'site_title' 				=> 	'Nom d\'emplacement',
		'forum_rules' 				=> 	'Règles de forum',
		'site_style' 				=> 	'Modèle d\'emplacement',
		'welcome_email' 			=> 	'Email bienvenu',
		'email_from' 				=> 	'Adresse de retour',
		'topics' 					=> 	'Sujets',
		'topic' 					=> 	'Sujet',
		'one_second_ago'			=> 	'1 seconde il y a',
		'seconds_ago' 				=> 	'secondes il y a',
		'one_min_ago' 				=> 	'il y a 1 minute',
		'mins_ago' 					=> 	'minutes il y a',
		'today_at' 					=> 	'Aujourd\'hui à',
		'by' 						=> 	'par',
		'logout' 					=> 	'Deconnexion',
		'forumrules' 				=> 	'<p>En enregistrant et en employant les forums, vous êtes d\'accord sur les règles suivantes:</p>
											<ul>
												<li>Être gentil à d\'autres</li>
												<li>Ne pas signaler le matériel blessant ou illégal</li>
												<li>Ne signaler aucun message qui est adulte ou offensive</li>
												<li>Aucun flamboyant, Spamming ou la publicité</li>
												<li>Ne pas détourner les fils d\'autres</li>
											</ul>
											<p>Vous devez être de treize ans ou plus pour signaler l\'information sur ces forum.</p>',
		'registerform'				=> 	'<p>Pour signaler sur ces forum vous devez être un utilisateur enregistré. Veuillez dactylographier un username et votre email address sous la forme ci-dessous.</p>
											<p>Nous <strong>ne vendrons pas</strong> ou n\'indiquerons pas votre email address à n\'importe qui. Il est nécessaire pour le verificationn et de sorte que nous puissions t\'envoyer un mot de passe temporaire.</p>',
		'invalid_login' 			=> 	'Nom d\'utilisateur inadmissible ou mot de passe.',
		'invalid_username' 			=> 	'Nom d\'utilisateur inadmissible. Doit être minuscule, contient les caractères alphanumériques seulement et pas commencent par un nombre.',
		'user_exists' 				=> 	'Nom d\'utilisateur déjà pris ou email address déjà en service.',
		'mail_error' 				=> 	'Il y avait une erreur envoyant le courrier. Veuillez entrer en contact avec le webmaster.',
		'register_success' 			=> 	'Enregistrement réussi. Regarder dans svp votre inbox d\'email pour votre mot de passe provisoire.',
		'db_error' 					=> 	'Il y avait une erreur avec la base de données.',
		'short_username' 			=> 	'Nom d\'utilisateur inadmissible. Doivent être au moins trois caractères de longueur.',
		'invalid_email' 			=> 	'Email address inadmissible.',
		'missing_message' 			=> 	'Vous n\avez pas dactylographié votre message. Veuillez retourner et le dactylographier.',
		'missing_subject' 			=> 	'Vous avez oublié d\écrire un sujet. Veuillez retourner et écrire un.',
		'welcome_email_message' 	=> 	"Bienvenue {site_title}.\n\nVotre information de compte est comme suit:\n\nNom d'utilisateur: {username}\nMot de passe: {password}\n\nC'est seulement un mot de passe provisoire, le changent svp la première fois que vous ouvrez une session.\n\nMerci de l'enregistrement.",
		'welcome_email_subject' 	=> 	'Bienvenue {site_title}',
		'user_banned' 				=> 	'Vous avez été interdits. Veuillez contacter un administrateur de forum.',
		'categories' 				=> 	'Categories',
		'category_delete_confirm1' 	=> 	'Are you completely <strong>sure</strong> you want to delete the category',
		'category_delete_confirm2' 	=> 	'and its child forums?',
		'no_categories' 			=> 	'There are no categories yet. You can add one using the form below.',
		'add_category' 				=> 	'Add category',
		'category' 					=> 	'Category',
		'date_format' 				=> 	'Date format',
		'base_address' 				=> 	'Base address'
	);